export const BRANCH_TYPES = [
  "Alemana",
  "Americana",
  "Arabe",
  "Argentina",
  "Caribeña",
  "Carnes",
  "Casera",
  "China",
  "Colombiana",
  "Comida Rápida",
  "Coreana",
  "De Autor",
  "Española",
  "Francesa",
  "Fusión",
  "Gourmet",
  "Griega",
  "Internacional",
  "Italiana",
  "Japonesa",
  "Libanesa",
  "Marroquí",
  "Mediterránea",
  "Mexicana",
  "Parrillada",
  "Peruana",
  "Pescados y Mariscos",
  "Pizzería",
  "Pollo en Brasas",
  "Portuguesa",
  "Rodizio",
  "Saludable",
  "Sandwiches",
  "Suiza",
  "Tailandesa",
  "Tapas",
  "Vasca",
  "Vegetariana",
  "Venezolana",
];
BRANCH_TYPES.sort();
